apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tsnfrmf11-go 
  janus-idp.io/tekton: tsnfrmf11-go
  backstage.io/kubernetes-id: tsnfrmf11-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tsnfrmf11-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  